name: Test and Checks

on:
  push:
    branches: [ dev ]

jobs:
  test:
    name: Test & coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Check out code
        uses: actions/checkout@v4
      - name: Run unit tests with coverage.
        run: |
          export TELEBOT_SECRET=${{ secrets.TELEBOT_SECRET }}
          export CHAT_ID=${{ secrets.CHAT_ID }}
          export USER_ID=${{ secrets.USER_ID }}
          export GOPATH=$(go env GOPATH)
          go clean -modcache
          go mod tidy
          make junit

      - name: Test Summary
        uses: test-summary/action@v1
        if: always()
        with:
          paths: |
            ./resources/cover/report.xml            

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v3
        if: always()
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./resources/cover/cover.out

      - name: Go cover diff
        uses: kskitek/coverdiff@v0.3.0
        if: always()