name: Test and Checks

on:
  push:
    branches: [ dev ]

jobs:
  test:
    name: Test & coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Check out code
        uses: actions/checkout@v4
      - name: Run unit tests with coverage.
        run: |
          go clean -modcache
          go mod tidy
          
          mkdir -p ./resources/cover
          rm -f ./resources/cover/tmp-cover.log;
          
          export TELEBOT_SECRET=${{ secrets.TELEBOT_SECRET }} && export CHAT_ID=${{ secrets.CHAT_ID }} && export USER_ID=${{ secrets.USER_ID }} && go test -p 1 ./... -coverprofile resources/cover/cover.out

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./resources/cover/cover.out